name: flutter_course
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter_osm_plugin: ^0.70.4
  geolocator: ^12.0.0
  geocoding: ^2.1.1
  flutter:
    sdk: flutter

  flutter_map: ^6.2.1
  latlong2: ^0.9.0
  http: ^1.3.0
  flutter_location_search: ^1.0.0

  google_maps_flutter: ^2.2.0
  google_maps_flutter_web: ^0.4.0+1


  device_preview: ^1.2.0
  cupertino_icons: ^1.0.8


dev_dependencies:
  shared_preferences: ^2.2.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/gf.jpg
    - images/gf.png
    - images/welcome_image.png
    - images/pic1.png
    - images/pic2.png
    - images/pic3.png

